language: generic
sudo: required
os: osx
cache:
  timeout: 600
  directories:
    - faucet-server/.build
jobs:
  include:
    - language: object-c
      osx_image: xcode11.2
      env:
        - SKIP_CKB_API_TESTS=1
      before_install:
        - cd faucet-server
      install:
        - brew install libsodium
        - brew tap vapor/tap
        - brew install vapor/tap/vapor
      script:
        - swift test

    - language: node_js
      node_js:
        - '12'
      before_install:
        - cd faucet-ui
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.0
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - travis_retry yarn install
      script:
        - git diff --exit-code yarn.lock
        - yarn build

